### ISSUE TITLE
No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb

### ISSUE THREAD

**Issue by zw1068** [pwnlandia/mhn#742] opened 2020-01-07 13:01 UTC
save me,please.

ubuntu18.04，fresh install.

I executed the script
`sudo ./install.sh`
when I finish 'MHN Configuration'，Program error：
`IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb'
`

all of it :
```
===========================================================
+ echo '  MHN Configuration'
  MHN Configuration
+ echo ===========================================================
===========================================================
+ python generateconfig.py
Do you wish to run in Debug mode?: y/n n
Superuser email: 123@163.com
Superuser password: 
Superuser password: (again): 
Passwords did not match. Try again
Superuser password: 
Superuser password: (again): 
Server base url ["http://117.14.9.149"]: http://192.168.1.9
Honeymap url ["http://192.168.1.9:3000"]: 
Mail server address ["localhost"]: 
Mail server port [25]: 
Use TLS for email?: y/n y
Use SSL for email?: y/n y
Mail server username [""]: 
Mail server password [""]: 
Mail default sender [""]: 
Path for log file ["/var/log/mhn/mhn.log"]: 
+ echo -e '\nInitializing database, please be patient. This can take several minutes'

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 42, in <module>
    from mhn.ui.views import ui
  File "/opt/mhn/server/mhn/ui/views.py", line 10, in <module>
    from mhn.ui.utils import get_flag_ip, get_sensor_name
  File "/opt/mhn/server/mhn/ui/utils.py", line 15, in <module>
    geoip2_reader = geoip2.database.Reader(MHN_SERVER_HOME+'/../../GeoLite2-City.mmdb')
  File "/opt/mhn/env/local/lib/python2.7/site-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/maxminddb/__init__.py", line 41, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/maxminddb/reader.py", line 51, in __init__
    with open(database, 'rb') as db_file:
IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb
```

I found my folders '/opt/GeoLite2-City/' and '/opt/GeoLite2-ASN/' are empty. 
by the way,I dont have 'mhn.db',the solution of  'mhn.db' is not suitable for me.

**Comment by d1str0** [comment] 2020-01-07 18:21
Closing as a dupe of #738

**Closed by d1str0** 2020-01-07 18:21 UTC
