### ISSUE TITLE
*IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb

### ISSUE THREAD

**Issue by vincenthalter** [pwnlandia/mhn#743] opened 2020-01-08 15:12 UTC
File "/opt/mhn/server/mhn/ui/utils.py", line 15, in <module> geoip2_reader = geoip2.database.Reader(MHN_SERVER_HOME+'/../../GeoLite2-City.mmdb') File "/opt/mhn/env/local/lib/python2.7/site-packages/geoip2/database.py", line 86, in __init__ self._db_reader = maxminddb.open_database(fileish, mode) File "/opt/mhn/env/local/lib/python2.7/site-packages/maxminddb/__init__.py", line 41, in open_database return maxminddb.reader.Reader(database, mode) File "/opt/mhn/env/local/lib/python2.7/site-packages/maxminddb/reader.py", line 51, in __init__ with open(database, 'rb') as db_file:
**IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb'** 

How can be this error fixed?
I`m just useing Ubuntu 16.04 after that i ran the ./install.py script.

**Comment by d1str0** [comment] 2020-01-08 17:31
Closing as a dupe of #738

**Closed by d1str0** 2020-01-08 17:31 UTC
Labels: duplicate
