### ISSUE TITLE
Missing repositories at the threatstream

### ISSUE THREAD

**Issue by rudyelaytonsera** [pwnlandia/mhn#866] opened 2023-11-30 09:32 UTC
Dear team,

I tried to run the `sudo ./install.sh` but after it run, at some point it failed.
I think there are some missing repositories when Installing menmosyne (https://github.com/threatstream/hpfeeds/) at this part.

![image](https://github.com/pwnlandia/mhn/assets/111834943/aec14448-0c3e-4153-b3de-e341d22b138b)

And here is the error shown in my terminal.

![Screenshot from 2023-11-30 16-18-50](https://github.com/pwnlandia/mhn/assets/111834943/ab3ccce2-8c3f-4355-b810-720d289ba855)

I would like to have your assistance fo this case.

Thank you very much for your support.

Best regards,
Rudye.

**Comment by wrharding** [comment] 2023-12-05 19:03
Closing. Dupe of #863. Focusing discussion there.

**Closed by wrharding** 2023-12-05 19:03 UTC
